Added option for doing software selection read-only
yast/skelcd-control-CASP pull request #12
Opened 2016-12-14 08:22 UTC by mchf

2016-12-14 12:48 UTC, imobachgs requested changes

2016-12-14 12:48 UTC, imobachgs commented on package/skelcd-control-CASP.changes
> +>>>>>>> upstream/master
Please, remove this leftover.

2016-12-14 12:48 UTC, imobachgs commented on package/skelcd-control-CASP.changes
> +- Added option for doing software selection read-only
*doing* or *making*? Let's check with our language expert :) @mvidner

2016-12-14 12:49 UTC, mchf commented on package/skelcd-control-CASP.changes
> +>>>>>>> upstream/master
grumpf. thx

2016-12-14 12:56 UTC, mvidner commented on package/skelcd-control-CASP.changes
> +- Added option for doing software selection read-only
Added *an* option for *making* *the* software selection read-only.

2016-12-14 12:57 UTC, mvidner commented
OK, where is the matching code for this option? Still to be written, or existing already? Please put it to the PR description.

2016-12-19 08:44 UTC, kobliha commented
@mchf It seems that the PR can't be merged

2016-12-20 09:13 UTC, mchf commented
Solved otherwise in the end

2016-12-20 09:13 UTC, closed without merging